### ISSUE TITLE
Add-on Fatals For Missing Or Unexpected Legacy Data

### ISSUE THREAD

**Issue by danielml01** [kadegray/statamic-country-and-region-fieldtypes#4]
We have users in a database (instead of flat files) imported from a legacy project. Unless country is not null and is a standard ISO number we get an exception screen.

For Unfound Codes/Data:
Call to a member function getLocalName() on null
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/CountryFieldtype.php: 110
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/RegionFieldtype.php: 135

For Null Data:
foreach() argument must be of type array|object, null given
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/CountryFieldtype.php: 107
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/RegionFieldtype.php: 132

This can be fixed by checking that the data is not null before running the foreach. Then checking the object is not null before running getLocalName();

This breaks all pages that use authentication on a user and the entire statamic control panel.
Thanks for any help you can provide!

**Comment by kadegray** [comment]
Hi @danielml01, thank you for opening this issue. I think you may be on 1.0.3, please try updating to 1.0.4 with `composer update kadegray/statamic-country-and-region-fieldtypes`.

This was a fix pushed a week ago, I believe it may fix your issue. https://github.com/kadegray/statamic-country-and-region-fieldtypes/issues/2

Please let me know whether it fixes it.

**Comment by danielml01** [comment]
This did not fully fix my issue. Although it fixed the issue of null values, it did not fix the issue of  unexpected data. If a code is malformed or is not a recognized code (ie spelled out) or is one of the ISO user-defined codes (ie XXX) the add-on still generates these errors:
Call to a member function getLocalName() on null
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/CountryFieldtype.php: 110
Call to a member function getLocalName() on null
vendor/kadegray/statamic-country-and-region-fieldtypes /src/Fieldtypes/RegionFieldtype.php: 135

For now we can address this from the data side, but you may still want to have the add-on "break pretty" in these cases

**Comment by kadegray** [comment]
I have pushed some changes in 1.1.0, https://github.com/kadegray/statamic-country-and-region-fieldtypes/commit/dc1450402ec8dc22e6e277a58aaa0b9cba5e5cf6, that I hope will help.

There is now a config on each of the FieldTypes called 'Render Invalid Value', it is false by default so you will have to toggle it on for each fieldtype. Once on, in the antlers it will render the the raw value if it is not ISO 3166 formatted.

I've refactored Country and Region so that now those errors you mentioned will no longer occur.

`composer update kadegray/statamic-country-and-region-fieldtypes`
